services:
  - type: web
    name: splice-app
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATA_DIR
        value: /var/data
      - key: DATABASE_FILE
        value: splice.db
      - key: MAX_CONTENT_LENGTH_MB
        value: "20"
    disks:
      - name: data
        mountPath: /var/data
        sizeGB: 1
